name: flutter_application_1
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^7.6.4
  # Bloc for state management
  flutter_bloc: ^8.1.3
  # Value equality
  equatable: ^2.0.5
  # Functional programming thingies
  dartz: ^0.10.1
  # Remote API
  connectivity: ^3.0.6
  http: ^1.1.0
  # Local cache
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

